repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black .
        language: system
        pass_filenames: false
        stages: [commit]
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8 . --exclude=.venv
        language: system
        pass_filenames: false
        stages: [commit]
-   repo: local
    hooks:
    -   id: requirements
        name: requirements
        entry: bash -c '.venv/bin/pip freeze > requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]
